FisioAmar/urls.py
# from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView
from core.views import control


urlpatterns = [
    path('core/', include('core.urls')),
    path('admin/', include('admin.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('', RedirectView.as_view(url=reverse_lazy('control'))),
    path('control/', control, name='control'),

]

core/urls.py
from django.urls import path
from core.views import *

urlpatterns = [
    path('control/', control, name='control'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    foto = models.ImageField(upload_to='images/profile_image', default='images/avatar/avatar-2.png', null=True, blank=True)


class Casa_de_Apoio(models.Model):
    nome = models.CharField(max_length=200)
    endereco = models.CharField(max_length=300, null=True, blank=True)
    telefone = models.CharField(max_length=50, null=True, blank=True)
    foto = models.ImageField(upload_to='images/profile_image', default='images/gallary/casa-de-apoio.jpg', null=True, blank=True)

    def __str__(self):
        return self.nome


class Paciente(models.Model):
    SEX_CHOICES = (('F', 'Feminino'), ('M', 'Masculino'))
    nome = models.CharField(max_length=200)
    nacimento = models.DateField()
    sexo = models.CharField(max_length=1, choices=SEX_CHOICES)
    foto = models.ImageField(upload_to='images/profile_image', default='images/avatar/avatar-5.png', null=True, blank=True)
    casa = models.ForeignKey(Casa_de_Apoio, on_delete=models.PROTECT)
    alertaPA = models.BooleanField(default=False)
    alertaGlicemia = models.BooleanField(default=False)

    def __str__(self):
        return self.nome

class Log(models.Model):
    datetime = models.DateTimeField(auto_now=True)
    acao = models.CharField(max_length=100)
    user = models.CharField(max_length=100)


class Visita(models.Model):
    ResultadosTestes1 = (('Normal', 'Normal'), ('Diminuido', 'Diminuido'))
    ResultadosTestes2 = (('Positivo', 'Positivo'), ('Negativo', 'Negativo'))
    ResultadosTestes3 = (('Normal', 'Normal'), ('Equilibrio Alterado', 'Equilibrio Alterado'))

    paciente = models.ForeignKey(Paciente, on_delete=models.PROTECT)
    data = models.DateField()

    altura = models.FloatField(null=True, blank=True)
    peso = models.FloatField(null=True, blank=True)
    imc = models.FloatField(null=True, blank=True)
    resultadoImc = models.CharField(max_length=20, null=True, blank=True)

    pa = models.CharField(max_length=10, null=True,blank=True)
    glicemia = models.IntegerField(null=True, blank=True)

    estesiometroMaos = models.CharField(max_length=100, null=True, blank=True)
    estesiometroPeDireito = models.CharField(max_length=100, null=True, blank=True)
    estesiometroPeEsquerdo = models.CharField(max_length=100, null=True, blank=True)

    reflexoPatelarDireito = models.CharField(max_length=15, choices=ResultadosTestes1, null=True, blank=True)
    reflexoPatelarEsquerdo = models.CharField(max_length=15, choices=ResultadosTestes1, null=True, blank=True)
    reflexoTricipitalDireito = models.CharField(max_length=15, choices=ResultadosTestes1, null=True, blank=True)
    reflexoTricipitalEsquedo = models.CharField(max_length=15, choices=ResultadosTestes1, null=True, blank=True)

    cordIdxIdxOpen = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)
    cordIdxNazOpen = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)
    cordIdxIdx = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)
    cordIdxNaz = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)
    cordDiadococinesia = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)
    cordCalcanharJoelho = models.CharField(max_length=15, choices=ResultadosTestes2, null=True, blank=True)

    tinetti = models.IntegerField(null=True, blank=True)
    GetUpAndGo = models.CharField(max_length=20, choices=ResultadosTestes3, null=True, blank=True)

templates/Base.html
<!DOCTYPE html>
<html lang="pt-br">
<!--================================================================================
Item Name: Materialize - Material Design Admin Template
Version: 4.0
Author: PIXINVENT
Author URL: https://themeforest.net/user/pixinvent/portfolio
================================================================================ -->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="msapplication-tap-highlight" content="no">
    <meta name="description" content="Materialize is a Material Design Admin Template,It's modern, responsive and based on Material Design by Google. ">
    <meta name="keywords" content="materialize, admin template, dashboard template, flat admin template, responsive admin template,">
    <title>FisioAmar</title>
    <!-- Favicons-->
    <link rel="icon" href="https://fisioamar.s3.amazonaws.com/static/images/favicon/FisioAmar-favicon.png" sizes="32x32">
    <!-- Favicons-->
    <link rel="apple-touch-icon-precomposed" href="https://fisioamar.s3.amazonaws.com/static/images/favicon/FisioAmar-favicon-apple.png">
    <!-- For iPhone -->
    <meta name="msapplication-TileColor" content="#00bcd4">
    <meta name="msapplication-TileImage" content="https://fisioamar.s3.amazonaws.com/static/images/favicon/FisioAmar-favicon-apple.png">
    <!-- For Windows Phone -->
    <!-- CORE CSS-->
    <link href="https://fisioamar.s3.amazonaws.com/static/css/themes/collapsible-menu/materialize.css" type="text/css" rel="stylesheet">
    <link href="https://fisioamar.s3.amazonaws.com/static/css/themes/collapsible-menu/style.css" type="text/css" rel="stylesheet">
    <!-- Custome CSS-->
    <link href="https://fisioamar.s3.amazonaws.com/static/css/custom/custom.css" type="text/css" rel="stylesheet">
    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="https://fisioamar.s3.amazonaws.com/static/vendors/perfect-scrollbar/perfect-scrollbar.css" type="text/css" rel="stylesheet">
    <link href="https://fisioamar.s3.amazonaws.com/static/vendors/jvectormap/jquery-jvectormap.css" type="text/css" rel="stylesheet">
    <link href="https://fisioamar.s3.amazonaws.com/static/vendors/flag-icon/css/flag-icon.min.css" type="text/css" rel="stylesheet">

    <link href="https://fisioamar.s3.amazonaws.com/static/vendors/sweetalert/dist/sweetalert.css" type="text/css" rel="stylesheet">
    <link href="https://fisioamar.s3.amazonaws.com/static/vendors/dropify/css/dropify.min.css" type="text/css" rel="stylesheet">
</head>
<body>
<!-- Start Page Loading -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->
<!-- //////////////////////////////////////////////////////////////////////////// -->
<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color gradient-45deg-purple-deep-orange gradient-shadow">
            <div class="nav-wrapper">
                {% block pesquisa %}
                {% endblock %}
                <ul class="right">
                    <li>
                        <a href="javascript:void(0);" class="waves-effect waves-block waves-light profile-button" data-activates="profile-dropdown">
                            <span class="avatar-status avatar-online">
                            <img src="{{ request.user.foto.url }}" alt="avatar">
                            <i></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <ul id="profile-dropdown" class="dropdown-content">
                    <li>
                        <a href="#modalPassword" class="grey-text text-darken-1 modal-trigger"><i class="material-icons">settings</i>Trocar Senha</a>
                    </li>
                    <li>
                        <a href="{% url 'logout' %}" class="grey-text text-darken-1"><i class="material-icons">keyboard_tab</i>Sair</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</header>
<!-- END HEADER -->
<!-- //////////////////////////////////////////////////////////////////////////// -->
<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper">
        <!-- START LEFT SIDEBAR NAV-->
        <aside id="left-sidebar-nav" class="nav-expanded nav-lock nav-collapsible">
            <div class="brand-sidebar">
                <h1 class="logo-wrapper">
                    <a href="{% url 'dashboard' %}" class="brand-logo darken-1">
                        <img src="https://fisioamar.s3.amazonaws.com/static/images/logo/hashtag.png" alt="materialize logo">
                        <span class="logo-text">FisioAmar</span>
                    </a>
                    <a href="#" class="navbar-toggler">
                        <i class="material-icons">radio_button_checked</i>
                    </a>
                </h1>
            </div>
            <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class="no-padding">
                    <ul class="collapsible" data-collapsible="accordion">
                        <li class="bold">
                            <a href="{% url 'dashboard'%}" class="waves-effect waves-cyan">
                                <i class="material-icons">dashboard</i>
                                <span class="nav-text">Dashboard</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a href="{% url 'list-users'%}" class="waves-effect waves-cyan">
                                <i class="material-icons">account_circle</i>
                                <span class="nav-text">Usuários</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a href="{% url 'list-lares'%}" class="waves-effect waves-cyan">
                                <i class="material-icons">home</i>
                                <span class="nav-text">Casas de Apoio</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a href="{% url 'list-pacientes' %}" class="waves-effect waves-cyan">
                                <i class="material-icons">account_circle</i>
                                <span class="nav-text">Pacientes</span>
                            </a>
                        </li>
                        <li class="bold">
                            <a href="{% url 'logs' %}" class="waves-effect waves-cyan">
                                <i class="material-icons">list</i>
                                <span class="nav-text">Logs</span>
                            </a>
                        </li>
                    </ul>
                </li>
            </ul>
            <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only gradient-45deg-light-blue-cyan gradient-shadow">
                <i class="material-icons">menu</i>
            </a>
        </aside>
        <!-- END LEFT SIDEBAR NAV-->
        <!-- //////////////////////////////////////////////////////////////////////////// -->
        <!-- START CONTENT -->
        <section id="content">
            <!--start container-->
            <div class="container">


                {% block main %}
                {% endblock %}
            </div>
        </section>


    </div>
    <!-- END WRAPPER -->
</div>
<!-- END MAIN -->

<!-- Modal Trigger -->

<!-- Modal Structure -->
<div id="modalPassword" class="modal" style="z-index: 1003; display: none; opacity: 0; transform: scaleX(0.7); top: 4%;">
    <form action="{% url 'trocarsenha' %}" method="post">
        {% csrf_token %}
        <div class="modal-content">
                <h5 class="breadcrumbs-title">Trocar Senha</h5>
                <label>Nova Senha</label>
                <input name="password" type="password">
        </div>
        <div class="modal-footer">
            <a class="modal-action modal-close waves-effect waves-light  btn  gradient-45deg-red-pink gradient-shadow z-depth-4">Cancelar</a>
            <button  class="modal-action modal-close waves-effect waves-light  btn gradient-45deg-green-teal gradient-shadow z-depth-4">Salvar</button>
        </div>
    </form>
</div>
<!-- //////////////////////////////////////////////////////////////////////////// -->
<!-- START FOOTER -->
<footer class="page-footer gradient-45deg-purple-deep-orange">
    <div class="footer-copyright">
        <div class="container">
            <span>Copyright ©
              <script type="text/javascript">
                document.write(new Date().getFullYear());
              </script>  All rights reserved.</span>
            <span class="right hide-on-small-only">Developed in Django </span>
        </div>
    </div>
</footer>
<!-- END FOOTER -->
<!-- ================================================
Scripts
================================================ -->
<!-- jQuery Library -->
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/materialize.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/prism/prism.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/scripts/page-item.js"></script>
<script src="https://fisioamar.s3.amazonaws.com/static/vendors/masonry.pkgd.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/chartjs/chart.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/dropify/js/dropify.min.js"></script>
<script src="https://fisioamar.s3.amazonaws.com/static/vendors/imagesloaded.pkgd.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/angular.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/vendors/sweetalert/dist/sweetalert.min.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/plugins.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/scripts/extra-components-sweetalert.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/scripts/form-file-uploads.js"></script>
<script type="text/javascript" src="https://fisioamar.s3.amazonaws.com/static/js/custom-script.js"></script>
{% block script %}
{% endblock %}


</body>
</html>

templates/dashboard.html
{% extends 'Base.html' %}


{% block main %}
    <div class="container">
        <!--card stats start-->
        <div id="card-stats">
            <div class="row">
                <div class="col s12 m6 l3">
                    <div class="card gradient-45deg-light-blue-cyan gradient-shadow min-height-100 white-text">
                        <div class="padding-4">
                            <div class="col s7 m7">
                                <i class="material-icons background-round mt-5">perm_identity</i>
                                <p>Usuários</p>
                            </div>
                            <div class="col s5 m5 right-align">
                                <h3 class="mb-0">{{ users|length }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l3">
                    <div class="card gradient-45deg-amber-amber gradient-shadow min-height-100 white-text">
                        <div class="padding-4">
                            <div class="col s7 m7">
                                <i class="material-icons background-round mt-5">home</i>
                                <p>Casas de Apoio</p>
                            </div>
                            <div class="col s5 m5 right-align">
                                <h3 class="mb-0">{{ casas|length }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l3">
                    <div class="card gradient-45deg-red-pink gradient-shadow min-height-100 white-text">
                        <div class="padding-4">
                            <div class="col s7 m7">
                                <i class="material-icons background-round mt-5">assignment_ind</i>
                                <p>Pacientes</p>
                            </div>
                            <div class="col s5 m5 right-align">
                                <h3 class="mb-0">{{ pacientes|length }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col s12 m6 l3">
                    <div class="card gradient-45deg-green-teal gradient-shadow min-height-100 white-text">
                        <div class="padding-4">
                            <div class="col s7 m7">
                                <i class="material-icons background-round mt-5">assignment_turned_in</i>
                                <p>Visitas</p>
                            </div>
                            <div class="col s5 m5 right-align">
                                <h3 class="mb-0">{{ visitas|length }}</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col s12 m12 l6">
            <div class="card-panel" style="overflow-x:auto;">
                <img src="https://fisioamar.s3.amazonaws.com/static/images/logo/FisioAmar-lat.png" alt="" class="responsive-img valign">
            </div></div>
        <div class="row">
            <div class="col s12 m12 l6">
                <div class="card-panel" style="overflow-x:auto;">
                    <h4 class="header2">Ultimos Pacientes</h4>
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Data de Nacimento</th>
                            <th>Sexo</th>
                            <th>Casa de Apoio</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for paciente in ultimosPacientes %}
                            <tr>
                                <td>{{ paciente.nome  }}</td>
                                <td>{{ paciente.nacimento|date:"d/m/Y" }}</td>
                                <td>{{ paciente.sexo }}</td>
                                <td>{{ paciente.casa }}</td>
                                <td>
                                    <a href="{% url 'edit-paciente' paciente.id %}" class="btn-floating waves-effect waves-light gradient-45deg-light-blue-cyan gradient-shadow"><i class="material-icons">edit</i></a>
                                    <a id="{% url 'delete-paciente' paciente.id %}" class="btn-floating btn-warning-cancel waves-effect waves-light gradient-45deg-red-pink gradient-shadow"><i class="material-icons">delete</i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col s12 m12 l6">
                <div class="card-panel" style="overflow-x:auto;">
                    <h4 class="header2">Últimas Visitas</h4>
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Data</th>
                            <th>Paciente</th>
                            <th>Casa de Apoio</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for visita in ultimasVisitas %}
                            <tr>
                                <td>{{ visita.data|date:"d/m/Y"  }}</td>
                                <td>{{ visita.paciente }}</td>
                                <td>{{ visita.paciente.casa }}</td>
                                <td>
                                    <a href="{% url 'edit-visita' visita.paciente.id visita.id %}" class="btn-floating waves-effect waves-light gradient-45deg-light-blue-cyan gradient-shadow"><i class="material-icons">edit</i></a>
                                    <a id="{% url 'delete-visita' visita.paciente.id visita.id %}" class="btn-floating btn-warning-cancel waves-effect waves-light gradient-45deg-red-pink  gradient-shadow"><i class="material-icons">delete</i></a>
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col s12 m12 l6">
                <div class="card-panel" style="overflow-x:auto;">
                    <h4 class="header2">Pacientes com Hipertensão</h4>
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Casa de Apoio</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for paciente in pacientes%}
                            {% if paciente.alertaPA %}
                                <tr>
                                    <td>{{ paciente.nome }}</td>
                                    <td>{{ paciente.casa }}</td>
                                    <td>
                                        <a href="{% url 'paciente' paciente.id %}" class="btn-floating waves-effect waves-light gradient-45deg-light-blue-cyan gradient-shadow"><i class="material-icons">info</i></a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col s12 m12 l6">
                <div class="card-panel" style="overflow-x:auto;">
                    <h4 class="header2">Pacientes com Diabetes</h4>
                    <table class="bordered highlight">
                        <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Casa de Apoio</th>
                            <th>Ação</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for paciente in pacientes%}
                            {% if paciente.alertaGlicemia %}
                                <tr>
                                    <td>{{ paciente.nome }}</td>
                                    <td>{{ paciente.casa }}</td>
                                    <td>
                                        <a href="{% url 'paciente' paciente.id %}" class="btn-floating waves-effect waves-light gradient-45deg-light-blue-cyan gradient-shadow"><i class="material-icons">info</i></a>
                                    </td>
                                </tr>
                            {% endif %}
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/lar-form.html
{% extends 'Base.html' %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title">Casa de Apoio</h5>
            </div>
        </div>
    </div>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card-panel">
            <div class="row">
                {{ form }}
            </div>
            <br>
            <button class="btn purple accent-3 waves-effect waves-light col s12 z-depth-5">Salvar</button>
        </div>
    </form>
{% endblock %}

templates/lares.html
{% extends 'Base.html' %}

{% block pesquisa %}
    <div class="header-search-wrapper hide-on-med-and-down sideNav-lock">
        <form method="post">
            {% csrf_token %}
            <i class="material-icons">search</i>
            <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Buscar Casa de Apoio" />
        </form>
    </div>
{% endblock %}

{% block main %}
    <div class="container" style="padding-top: 20px;">
        <div class="header-search-wrapper card hide-on-large-only input-field" >
            <form method="post">
                {% csrf_token %}
                <i class="material-icons prefix" style="padding-top: 7px; padding-left: 7px;">search</i>
                <input type="text" name="Search" class="header-search-input z-depth-2" placeholder="Buscar Casas de Apoio" />
            </form>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title">Casas de Apoio</h5>
            </div>
        </div>
    </div>
    <div class="section">
        <div id="item-posts" class="row">
            <div class="item-sizer"></div>
            {% for lar in lares %}
            <div class="item product">
                <div class="card">
                    <div class="card-image waves-effect waves-block waves-light">
                        <a href="{% url 'lar' lar.id%}">
                            <img src="{{ lar.foto.url }}" height="300" alt="item-img" >
                        </a>
                    </div>
                    <ul class="card-action-buttons">
                        <li>
                            <a href="{% url 'edit-lar' lar.id %}" class="btn-floating waves-effect waves-light gradient-45deg-light-blue-cyan gradient-shadow">
                                <i class="material-icons">edit</i>
                            </a>
                        </li>
                        <li>
                            <a id="{% url 'delete-lar' lar.id %}" class="btn-floating btn-warning-cancel waves-effect waves-light gradient-45deg-red-pink gradient-shadow">
                                <i class="material-icons">delete</i>
                            </a>
                        </li>
                    </ul>
                    <div class="card-content">
                        <div class="row">
                            <div class="col s12">
                                <p class="card-title grey-text text-darken-4"><a href="#" class="grey-text text-darken-4">{{ lar.nome }}</a>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%  endfor %}
        </div>
        <!--/ end items list -->
    </div>
    <div class="fixed-action-btn" style="bottom: 50px; right: 19px;">
        <a href="{%  url 'new-lar' %}" class="btn-floating btn-large waves-effect waves-light gradient-45deg-indigo-purple gradient-shadow">
            <i class="material-icons">add</i>
        </a>
    </div>
{% endblock %}

templates/logs.html
{% extends 'Base.html' %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title">Logs</h5>
            </div>
        </div>
    </div>
    <div class="card-panel">
        <!-- statr items list -->
        <div class="col-12">
            <table class="bordered highlight">
                <thead>
                <tr>
                    <th>Data e Hora</th>
                    <th>Usuário</th>
                    <th>Ação</th>
                </tr>
                </thead>
                <tbody>
                {% for log in logs %}
                <tr>
                    <td>{{ log.datetime }}</td>
                    <td>{{ log.user }}</td>
                    <td>{{ log.acao }}</td>
                </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <!--/ end items list -->
    </div>





{% endblock %}

templates/user-new.html
{% extends 'Base.html' %}


{% block main %}
    <div class="container">
        <div class="row">
            <div class="col s10 m6 l6">
                <h5 class="breadcrumbs-title">Usuário</h5>
            </div>
        </div>
    </div>
    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="card-panel">
                <div class="row">
                    <div class="input-field col s6">
                        {{ form.first_name }}
                        <label for="first_name">Nome</label>
                    </div>
                    <div class="input-field col s6">
                        {{ form.last_name }}
                        <label for="last_name">Sobrenome</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.email }}
                        <label for="email">Email</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.username }}
                        <label for="username">Username</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.password }}
                        <label for="password">Senha</label>
                    </div>
                </div>
                <div class="row">
                    <div class="input-field col s12">
                        {{ form.foto }}
                        <label for="id_foto">Foto:</label>
                    </div>
                </div>
            </div>
            <br>
            <button class="btn purple accent-3 waves-effect waves-light col s12 z-depth-5">Salvar</button>
        </form>
    </div>
{% endblock %}